### ISSUE TITLE
No trailing slash makes build fail

### ISSUE THREAD

**Issue by olanod** [chevdor/srtool-cli#12]
I'm running `srtool build -p <some-package>` on Linux and getting an error  `/tmpcargo: no such file or directory`. Likely due to [this line](https://github.com/chevdor/srtool-cli/blob/master/cli/src/main.rs#L71) where `env::temp_dir().display()` seems to return a path without trailing slash when the slash is expected.

**Comment by chevdor** [comment]
Hi Daniel, thanks for the report.
Indeed, the way the `tmpdir` was generated was not very robust. This should now be fixed in master. The issue has been closed but feel free to re-open if the fix does not work.
