### ISSUE TITLE
syntax error: operand expected (error token is "<body>You > 10#are")

### ISSUE THREAD

**Issue by crystalin** [chevdor/srtool-cli#16]
Using 0.6.0 (from github)

```
>  srtool -j build --default-features evm-tracing --package moonbase-runtime
...
/srtool/lib.sh: line 23: ((: 10#<html><body>You > 10#are: syntax error: operand expected (error token is "<body>You > 10#are")
/srtool/lib.sh: line 27: ((: 10#<html><body>You < 10#are: syntax error: operand expected (error token is "<body>You < 10#are")
```

I'll see if I get the time to look at it

**Comment by chevdor** [comment]
I think this issue has been fixed already but I am checking again against your current master. So far so good.
It is easier to test using `srtool build --app --default-features evm-tracing --package moonbase-runtime` (not using `-j`)

**Comment by crystalin** [comment]
Thank you :)
