### ISSUE TITLE
 Rust nightly not installed, please install it!

### ISSUE THREAD

**Issue by hqwangningbo** [chevdor/srtool-cli#25]
srtool-cli 0.11.0

rust version: rustc 1.67.0-nightly (96ddd32c4 2022-11-14)

Obviously it has been installed, but it will report that it is not installed

**Comment by wilwade** [comment]
@hqwangningbo If you want you can switch back to the older version of the image with `SRTOOL_TAG="1.66.1"`

**Comment by chevdor** [comment]
@hqwangningbo It would be useful to know exactly what commnd your typed and what error you got.
The content of this issue is a bit light for me to start anywhere besides telling you that you are using 0.11.0 and that 0.12.0 is out.

**Comment by hqwangningbo** [comment]
thanks. @chevdor @wilwade
