### ISSUE TITLE
Exit code pass through

### ISSUE THREAD

**Issue by wilwade** [chevdor/srtool-cli#26]
The exit code from the underlying command doesn't pass through to be the exit code of srtool-cli.

https://github.com/chevdor/srtool-cli/blob/dc28ec5a094f1c9eae3911cec75b81a04ce1f9f1/cli/src/main.rs#L129-L135

I can throw up a PR to fix it, but will need help testing it on Windows.

**Comment by chevdor** [comment]
I am not convinced there are many Windows users so don't bother too much  :)
CI is checking that it builds: https://github.com/chevdor/srtool-cli/blob/master/.github/workflows/weekly-check.yml

What you can do is drop a log pointing to this issue for the Windows case and see if a Windows user is willing to help testing. I don't have Windows machine and I don't really want to spend time checking this out. The implementation has only be done with Windows in mind to give it a chance :)

Your PR is very welcome.

**Comment by wilwade** [comment]
@chevdor Got the PR up. It looks like Windows is happy with the solution, so I think we are good there.
